### ISSUE TITLE
Cannot add items to shopping list-create new shopping list-edit some of items quantity conversion ratio

### ISSUE THREAD

**Issue by nikmak88** [hassio-addons/addon-grocy#476]
Hello,
I have grocy installed on a home assistant instance as an add-on
Everything was working on version 0.23 and since I updated to 0.24 the following buttons only work by opening them in a new tab:
- Add item in the Shopping List menu
- New Shopping List in the Shopping List menu
- Edit Shopping List in the Shopping List menu
- Master Data - Products - In the item menu - Button to add the item to the shopping list
- Master Data - Products - Inside the item edit menu - Button to change the quantity ratios

None of these work by tapping from a phone device or click on a computer.
When opened in new tab, everything works. 

Tested with vanilla web browsers without ad blockers, the home assistant application and all behave the same. 
There are no evident logs in the console of the browser.
Noticed that all these have in common the /api/hassio_ingress/UqWZbsxSGbESI07tGsT8kH8YVoH1N39yYgfyaKKUP_w/shoppinglistitem/ prefix (shoppinglistitem object)
Here is a sample link from the Add item button from the shopping list menu.
http://IP:8123/api/hassio_ingress/UqWZbsxSGbESI07tGsT8kH8YVoH1N39yYgfyaKKUP_w/shoppinglistitem/new?embedded&list=1

**Comment by KoRRo** [comment]
Same here. I didn't notice the new tab workaround, thank you for suggesting it, at least it's not totally unusable.

**Comment by valadas** [comment]
I had issues with the edit icons on stock entries too unless I open grocy in another tab too.

**Comment by MobiuSRIT** [comment]
> I had issues with the edit icons on stock entries too unless I open grocy in another tab too.

Exactly the same here.  When inside the HA interface, I can't add things in various screens.  As soon as I break it out of that, it seems to work.

**Comment by vincegre** [comment]
+1, same here, thought at first it was an issue with my browser but same on other computers !

**Comment by digitalcajun** [comment]
Cannot edit Tasks / Userfields / Userentities since updating to 0.24.

**Comment by hadrabant** [comment]
+1, 0.23 works fine

**Comment by berrnd** [comment]
[Grocy v4.4.2](https://grocy.info/changelog#v4.4.2) where this should be fixed dropped just now.

**Comment by schumi2309** [comment]
Still no solution?
I don’t even know how to create a new shopping list!
what is happening?

**Comment by alexlmiller** [comment]
also happens with adding chores

**Comment by vsutra** [comment]
> I've checked, identified and fixed what this most likely is about - see [grocy/grocy#2686](https://github.com/grocy/grocy/issues/2686).

This is still an issue in 4.4.2, you get cross origin errors for those dialogs:

![Image](https://github.com/user-attachments/assets/e73716b4-07c0-4c63-aade-3d928653e853)

**Comment by berrnd** [comment]
> This is still an issue in 4.4.2, you get cross origin errors for those dialogs:

That's not correct or has at least nothing to do with the originally reported and in https://github.com/grocy/grocy/issues/2686 identified and fixed problem.

When you run Grocy in an `iframe` and the `iframe` site uses a different (base) URL than Grocy itself, than this is the unsurprising "error" you get. If you want to run such a complex setup for whatever reason, you need to consider the [same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) and instruct your web server to send according [CORS headers](https://developer.mozilla.org/en-US/docs/Web/Security/Practical_implementation_guides/CORS).

A real-world example that illustrates this:

Proof of a working example: https://demo-prerelease.grocy.info/_debug_grocy_iframe_working.html
Why does that work? Because the "iframe page" runs under the same domain `demo-prerelease.grocy.info` as Grocy itself.

Proof of a not working example: https://demo-prerelease.grocy.info/_debug_grocy_iframe_not_working.html
Why does that not work? Because the "iframe page" runs under a different domain (`demo-prerelease.grocy.info`) as Grocy itself (`demo.grocy.info`).

Most likely just some URL related settings are wrong on your side, since I guess in a normal HA environment the mentioned base URL (domain) should be the same across all resource hosted/provide by HA and so also for Grocy.

**Comment by vsutra** [comment]
> > This is still an issue in 4.4.2, you get cross origin errors for those dialogs:
> 
> That's not correct or has at least nothing to do with the originally reported and in [grocy/grocy#2686](https://github.com/grocy/grocy/issues/2686) identified and fixed problem.
> 
> When you run Grocy in an `iframe` and the `iframe` site uses a different (base) URL than Grocy itself, then this is the unsurprising "error" you get. If you want to run such a complex setup for whatever reason, you need to consider the [same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) and instruct your web server to send according [CORS headers](https://developer.mozilla.org/en-US/docs/Web/Security/Practical_implementation_guides/CORS).
> 
> A real-world example that illustrates this:
> 
> Proof of a working example: https://demo-prerelease.grocy.info/_debug_grocy_iframe_working.html Why does that work? Because the "iframe page" runs under the same domain `demo-prerelease.grocy.info` as Grocy itself.
> 
> Proof of a not working example: https://demo-prerelease.grocy.info/_debug_grocy_iframe_not_working.html Why does that not work? Because the "iframe page" runs under a different domain (`demo-prerelease.grocy.info`) as Grocy itself (`demo.grocy.info`).
> 
> Most likely just some URL related settings are wrong on your side, since I guess in a normal HA environment the mentioned base URL (domain) should be the same across all resources hosted/provided by HA and so also for Grocy.

Version 4.3.0 works fine, which is why I suspected it was the same problem. I've tried manipulating the CORS to accept everything under the sun, but it still wouldn't work, and when I downgraded to 4.3.0, voila it worked fine though missing the features of 4.4.x.

Not sure whether this matters, but I'm not using Grocy as a HA add-on, it's just embedded in an iframe (tho coincidentally it happened to be in HA that I'm embedding it).

**Comment by vsutra** [comment]
Seems like window.top and window.parent is being referenced by grocy.js which is causing the CORS issues. Unfortunately HA is a pain to setup the right CORS, or it doesn't seem to work properly for me, so modifying that block of code in grocy.js with try/catch when trying to test windows.top does the trick here specifically within GetTopmostWindow().

As for window.parent, since GetTopmostWindow() is fixed, using that instead of window.parent (basically I replaced all instances of window.parent with GetTopmostwindow()) works.

@berrnd Not sure whether you want to include it in future versions, appreciate it if you do, but I can understand if you don't.

**Comment by berrnd** [comment]
> Not sure whether this matters, but I'm not using Grocy as a HA add-on, it's just embedded in an iframe

Yet again: Of course that's the and the only problem. Not specifically related to HA, related to when running Grocy in an `iframe`, no matter if under HA or not - see my, to HA unrelated, real-world examples above.

&nbsp;
> Seems like window.top and window.parent is being referenced by grocy.js which is causing the CORS issues.

Also yet again: Was the case and exactly the problem in Grocy v4.4.0 and v4.4.1 and was of course my fault, as always. Has been fixed in v4.4.2 and is tracked in https://github.com/grocy/grocy/issues/2686. Also my real-world illustrations above proof that running Grocy in an `iframe` now properly works again, when the CORS stuff is considered.

&nbsp;
> basically I replaced all instances of window.parent with GetTopmostwindow()

Well, more or less the same I did in https://github.com/grocy/grocy/commit/2b994fd2eecd187c31cb440d536d0fdf61c36d62.

&nbsp;
> Not sure whether you want to include it in future versions

I don't know what and don't see anything as of now (in v4.4.2; remember that this here still uses Grocy v4.4.1 as of the current [v0.24.0 release](https://github.com/hassio-addons/addon-grocy/releases/tag/v0.24.0)) which doesn't work related to running Grocy in an `iframe`, when the basics around are configured accordingly.

Also having Grocy work inside the HA add-on is not my primary goal, but I'm of course open to add stuff if it generally makes sense. If something beyond that is needed, the add-on needs to care about that itself (like it already does with [that friendly named thing](https://github.com/hassio-addons/addon-grocy/blob/main/grocy/rootfs/patches/fix_braindamage.patch)). Hopefully now it's finally clear what the problem was. Personal recommendation: To unleash having control over everything (and get releases sooner), simply use a normal/separate installation of Grocy.

**Comment by vsutra** [comment]
Not sure I fully follow on your remarks with regards to 4.4.1 vs 4.4.2, I'm using the latest docker image of Grocy from linuxserver (v4.4.2-ls286) , so unless they made a mistake in packaging the versions, I assumed I was on 4.4.2. 

Anyways, thanks for the feedback.

**Comment by berrnd** [comment]
> I assumed I was on 4.4.2

If you have there any reference to `window.top` (beside two in `GetTopmostWindow`; you've mentioned you've replaced "all instances"), then things went weird since that's not [the shipped state](https://github.com/search?q=repo%3Agrocy%2Fgrocy%20window.top&type=code).

**Comment by vsutra** [comment]
I just downloaded 4.4.5 direct (not using the docker-grocy). Grocy.js still references window.top without being in a try block. The problem with that is, it will throw an CORS error and the dialog boxes will not function
current:
`if (window.top.IsGrocy)
	{
		// If the top window is Grocy (so when we're currently not running in an iframe) return that immediately
		return window.top;
	}
`
proposed:
`
	try {
		if (window.top.IsGrocy)
			{
					// If the top window is Grocy (so when we're currently not running in an iframe) return that immediately
					return window.top;
			}
		}`

**Comment by berrnd** [comment]
It's getting pretty off-topic here and I normally don't hijack threads, remember that this is about the Grocy HA Add-on. (!!!) You're talking lately about a different setup (clearly running Grocy outside of HA) where then the parent site (hosting the `iframe`) and Grocy itself most likely have different origins. That's not the case for when using the Add-On (!!!) and wasn't in scope of anything referenced here. It's very frustrating to always mix up just like everything. That said, I'm out here for now.

&nbsp;
> I just downloaded 4.4.5

Interesting, the latest Grocy release is v4.5.0.

&nbsp;
> it will throw an CORS error

Not when you finally get your CORS headers sorted if you really need that complexity. You're proposed change is simply a workaround for need doing your own homework.

&nbsp;
Final and last conclusion from my side on this: The problem originally reported here (and in other threads in this repo) will be resolved once this Add-On upgrades to Grocy >= v4.4.2.

**Comment by gerardsamara** [comment]
Hello,
I just installed HA 2025.5.0 and i noticed that the fix is still not delivered.
And coming to the Github  issue #476 , i see tha the fix is not planned.
I do not understand why because the addon grocy still does not work .
Hope the a fix will be available

**Comment by evlo** [comment]
I think these issues here are being closed as it is issue in grocy and not HA addon for groccy. But not sure, it is confusing.

**Comment by thunfisch987** [comment]
It's fixed in grocy but the addon is not updated yet
